grupuri/api/urls.py

from django.conf.urls import url

from .views import (
    BoardListCreateAPIView,
    BoardRetrieveUpdateDestroyAPIView,
    GetSubscribedBoards,
    SubscribeBoardView,
    TrendingBoardsList,
)

urlpatterns = [
    url(r'^boards/$', BoardListCreateAPIView.as_view(), name='list_or_create_boards'),
    url(r'^boards/(?P<slug>[-\w]+)/$',
        BoardRetrieveUpdateDestroyAPIView.as_view(),
        name='retrieve_or_update_or_destroy_boards'),
    url(r'^actions/subscribe/$', SubscribeBoardView.as_view()),
    url(r'^top_five_boards/$', TrendingBoardsList.as_view()),
    url(r'^user_subscribed_boards/$', GetSubscribedBoards.as_view()),
]

grupuri/forms.py

from django import forms

from .models import Board


class BoardForm(forms.ModelForm):
    """
    Form that handles board data.
    """
    description = forms.CharField(widget=forms.Textarea(attrs={'rows': 5}))
    cover = forms.ImageField(widget=forms.FileInput(),
                             help_text="Image dimensions should be <b>900 &#10005; 300</b>.",
                             required=False)

    class Meta:
        model = Board
        fields = ('title', 'description', 'cover')

grupuri/templates/boards/banned_users.html
{% extends "base.html" %}
{% load staticfiles %}
{% load boards_tags %}
{% load humanize %}

{% block title %}<title>Banned Users</title>{% endblock %}

{% block content %}

{% include "includes/page_heading.html" with text="Banned Users" %}
{% if users %}
<p class="text-muted text-center">Unban user if they were banned by mistake from board.</p>
{% endif %}

{% for user in users %}
<div class="card mb-2" style="border:none; border-bottom:1px solid #dcd7d7;">
  <div class="card-body p-4">

    <div class="text-center" style="float:left; width:10%;">
      {% if user.profile.get_picture %}
      <img src="{{user.profile.get_picture}}" class="rounded" width="50px" height="50px">
      {% endif %}
    </div>

    <div style="float:right; width:90%;">
      <h6>
        <a href="{% url 'user_profile' user.username %}"
           class="card-link">{{ user.profile.screen_name }}</a> &nbsp; &nbsp; &nbsp;
        <a href="{% url 'ban_user' board.slug user.id %}"
           class="btn btn-outline-secondary btn-sm">Unban User</a>
      </h6>
    </div>
  </div>
</div>
{% empty %}
<p class="text-muted text-center">No User Banned Yet!</p>
{% endfor %}

{% endblock content %}

grupuri/templates/boards/board.html
{% extends "base.html" %}

{% block title %}<title>{{ board.title }} | </title>{% endblock %}

{% block content %}

{% include "includes/page_heading.html" with text=board.title|upper %}
{% if subjects %}
  {% include "includes/partial_subject.html" with subjects=subjects %}
{% else %}
  <div class="card p-4 my-4 mx-0">
    <h6 class="text-center">No Subjects Found</b></h6>
    <div style="margin:0 auto;">
    <p class="text-muted">Be the first one to post a subject in this board.</p>
    </div>
  </div>
{% endif %}

{% endblock %}

grupuri/templates/boards/edit_board_cover.html
{% extends "base.html" %}
{% load crispy_forms_tags %}
{% block title %}<title>Change Your Board Cover | </title>{% endblock %}


{% block form_content %}

{% include "includes/page_heading.html" with text="Change Your Board Cover" %}
{% if board_form.errors %}
  <div class="alert alert-danger alert-dismissible fade show" role="alert">
    {{board_form.errors}}
    <button type="button" class="close" data-dismiss="alert" aria-label="Close">
    <span aria-hidden="true">&times;</span>
    </button>
  </div>
{% endif %}

<form method="POST" enctype="multipart/form-data">
  {% csrf_token %}
  <div class="form-group">
    <label for="id_cover">Cover photo</label>
    <input type="file" class="form-control-file" id="id_cover" name="cover" accept="image/*">
  </div>
   <button type="submit" class="btn btn-primary btn-block" id="submit_cover">Submit</button>
</form>


<script type="text/javascript">
// Check file size
$(document).ready(function(){
  $("input#id_cover").on("change", function () {
    var file_size = this.files[0].size;
    if (file_size > 2097152) {
      alert("Image size should be less than 2 megabytes.")
      $("button#submit_cover").prop('disabled', true);
    } else {
        $("button#submit_cover").prop('disabled', false);
    }
  });
});
</script>

{% endblock %}

grupuri/templates/boards/new_board.html
{% extends "base.html" %}
{% load crispy_forms_tags %}

{% block title %}<title>Create Board | </title>{% endblock %}

{% block form_content %}
{% include "includes/page_heading.html" with text="Create Board" %}

<form action="{% url 'new_board' %}" method="post" enctype="multipart/form-data">
  {% csrf_token %}
  {{ board_form|crispy }}
 <button type="submit" class="btn btn-success btn-block">Submit</button>
</form>
{% endblock %}

grupuri/templates/boards/user_created_boards.html
{% extends "base.html" %}

{% block title %}<title>Your boards | </title>{% endblock %}

{% block content %}

{% include "includes/page_heading.html" with text="Your Boards" %}
{% if user_boards %}
  {% include "includes/partial_board.html" with boards=user_boards %}
{% else %}
  <div class="card p-4 my-4 mx-0">
    <h6 class="text-center">No Boards Found</h6>
    <div style="margin:0 auto;">
    <p class="text-muted">You have not created any boards created yet.</p>
    </div>
  </div>
{% endif %}

<script type="text/javascript">
// Subscribe boards
$(document).ready(function(){
  $("a#subscribe_board").on("click", function () {
    {% if not request.user.is_authenticated %}
    window.location.href = "{% url 'login' %}";
    {% else %}
    var $msg=$(this);
    var $subscribe_url=$(this).attr("href");
    var $board_subscribers=$('span#board_subscribers')
    $.ajax({
      url: $subscribe_url,
      type: 'GET',
      success: function (data) {
        if ($msg.text() == 'Subscribe') {
          $msg.removeClass('btn-primary');
          $msg.addClass('btn-secondary');
          $msg.text('Unsubscribe');
          $board_subscribers.text(data + ' readers');
        } else if ($msg.text() == 'Unsubscribe') {
          $msg.removeClass('btn-secondary');
          $msg.addClass('btn-primary');
          $msg.text('Subscribe');
          $board_subscribers.text(data + ' readers');
        } else { console.log('Unexpected error!'); }
      }
    });
    {% endif %}
    return false;
  });
});
</script>

{% endblock %}

grupuri/templates/boards/user_subscription_list.html
{% extends "base.html" %}

{% block title %}<title>Subscription List | </title>{% endblock %}

{% block content %}

{% include "includes/page_heading.html" with text="Subscription List" %}
<div class="alert alert-light text-center" role="alert">
  Subscribe interesting boards to populate your home feed with interesting subjects.
</div>
{% if subscriptions %}
  {% include "includes/partial_board.html" with boards=subscriptions %}
{% else %}
  <div class="card p-4 my-4 mx-0">
    <h6 class="text-center">No Subscriptions Found</h6>
    <div style="margin:0 auto;">
    <p class="text-muted">You have not subscribed any boards yet.</p>
    </div>
  </div>
{% endif %}

{% endblock %}

grupuri/templates/boards/view_all_boards.html
{% extends "base.html" %}

{% block title %}<title>Subscribe Boards | </title>{% endblock %}

{% block content %}

{% include "includes/page_heading.html" with text="Subscribe Boards" %}
<div class="alert alert-light text-center" role="alert">
  Click the <span class="font-weight-bold">Subscribe</span> button to populate your home feed with interesting board's subjects.
</div>
{% if boards %}
  {% include "includes/partial_board.html" with boards=boards %}
{% else %}
  <div class="card p-4 my-4 mx-0">
    <h6 class="text-center">No Boards Found</h6>
    <div style="margin:0 auto;">
    <p class="text-muted">There are no boards created yet.</p>
    </div>
  </div>
{% endif %}

{% endblock %}