modele/api/urls.py
#!/usr/bin/env python3
# -*- coding: utf-8 -*-
from django.conf.urls import url

from .views import (
    ActiveThreadsList,
    StarSubjectView,
    SubjectListCreateAPIView,
    SubjectRetrieveUpdateDestroyAPIView,
)

urlpatterns = [
    url(r'^subjects/$', SubjectListCreateAPIView.as_view(), name='list_or_create_subjects'),
    url(r'^subjects/(?P<slug>[-\w]+)/$',
        SubjectRetrieveUpdateDestroyAPIView.as_view(),
        name='retrieve_or_update_or_destroy_subjects'),
    url(r'^actions/star/$', StarSubjectView.as_view()),
    url(r'^user_active_threads/$', ActiveThreadsList.as_view()),
]

modele/models.py
#!/usr/bin/env python3
# -*- coding: utf-8 -*-
from django.conf import settings
from django.contrib.auth.models import User
from django.db import models
from django.urls import reverse
from django.utils import timezone
from django.utils.html import escape

import bleach
from slugify import UniqueSlugify

from boards.models import Board


class Subject(models.Model):
    """
    Model that represents a subject.
    """
    title = models.CharField(max_length=150, db_index=True)
    slug = models.SlugField(max_length=150, null=True, blank=True)
    body = models.TextField(max_length=5000, blank=True, null=True)
    photo = models.ImageField(upload_to='subject_photos/', verbose_name=u"Add image (optional)", blank=True, null=True)
    author = models.ForeignKey(User, related_name='posted_subjects', on_delete=models.CASCADE)
    board = models.ForeignKey(Board, related_name='submitted_subjects', on_delete=models.CASCADE)
    points = models.ManyToManyField(settings.AUTH_USER_MODEL, related_name='liked_subjects', blank=True)
    mentioned = models.ManyToManyField(User, related_name='m_in_subjects', blank=True)
    rank_score = models.FloatField(default=0.0)
    active = models.BooleanField(default=True)
    created = models.DateTimeField(default=timezone.now)
    updated = models.DateTimeField(auto_now=True)

    class Meta:
        ordering = ('-created', )

    def __str__(self):
        """Unicode representation for a subject model."""
        return self.title

    def save(self, *args, **kwargs):
        if not self.slug:
            self.slug = subject_slugify(f"{self.title}")

        super().save(*args, **kwargs)

    def get_absolute_url(self):
        """Return absolute url for a subject."""
        return reverse('subject_detail', args=[self.board.slug, self.slug])

    @staticmethod
    def get_subjects(user=None):
        """Returns a list of subjects."""
        if user:
            subjects = Subject.objects.filter(active=True, author=user)
        else:
            subjects = Subject.objects.filter(active=True)
        return subjects

    @staticmethod
    def search_subjects(query, board=None):
        """Searches for subjects."""
        if board:
            search_results = Subject.objects.filter(active=True, title__icontains=query, board=board)
        else:
            search_results = Subject.objects.filter(active=True, title__icontains=query)
        return search_results

    def get_points(self):
        """Returns number of stars."""
        return self.points.count()

    def linkfy_subject(self):
        """Linkifies the subject body."""
        return bleach.linkify(escape(self.body))

    def set_rank(self):
        """Calculates the rank score of a subject."""
        GRAVITY = 1.2
        time_delta = timezone.now() - self.created
        subject_hour_age = time_delta.total_seconds()
        subject_points = self.points.count() - 1
        self.rank_score = subject_points / pow((subject_hour_age + 2), GRAVITY)
        self.save()


def subject_unique_check(text, uids):
    if text in uids:
        return False
    return not Subject.objects.filter(slug=text).exists()


subject_slugify = UniqueSlugify(unique_check=subject_unique_check,
                                to_lower=True,
                                max_length=80,
                                separator='_',
                                capitalize=False)

modele/templates/subjects/edit_subject.html
{% extends "base.html" %}
{% load crispy_forms_tags %}
{% block title %}<title>Edit Subject | </title>{% endblock %}

{% block form_content %}

{% include "includes/page_heading.html" with text="Edit Subject" %}
<form method="POST" enctype="multipart/form-data">
  {% csrf_token %}
  {{ subject_form|crispy }}

  <button type="submit" class="btn btn-primary btn-block" id="submit_subject">Submit</button>
</form>

<script type="text/javascript">
// Check file size
$(document).ready(function(){
  $("#id_photo").on("change", function () {
    var file_size = this.files[0].size;
    if (file_size > 2097152) {
      alert("Image size should be less than 2 megabytes.");
      $("button#submit_subject").prop('disabled', true);
    } else {
      $("button#submit_subject").prop('disabled', false);
    }
  });
});
</script>

{% endblock %}

modele/templates/subjects/home.html
{% extends "base.html" %}

{% block content %}

{% include "includes/page_heading.html" with text="Homepage" %}
{% include "includes/partial_subject.html" with subjects=subjects %}

{% endblock content %}

modele/templates/subjects/new_subject.html
{% extends "base.html" %}
{% load crispy_forms_tags %}

{% block title %}<title>Create New Post | </title>{% endblock %}

{% block form_content %}
{% include "includes/page_heading.html" with text="Create Post" %}

<form action="{% url 'new_subject' %}" method="post" enctype="multipart/form-data">
  {% csrf_token %}
  {{ subject_form|crispy }}
  <button type="submit" class="btn btn-primary btn-block">Submit</button>
</form>
{% endblock %}

modele/templates/subjects/subject.html
{% extends "base.html" %}
{% load boards_tags %}
{% load humanize %}
{% load emoticons_tags %}
{% load static %}

{% block title %}<title>{{ subject.title }} | </title>{% endblock %}

{% block meta_description %}{{ subject.body }}{% endblock %}

{% block content %}
<style>
    .card-styling { margin-bottom:10px; }
    .card-body-styling { padding:10px; }
    .star-partition { float:left; width:10%; text-align:center; padding-top:10px; }
    .body-partition { float:right; width:90%; }
    .card-photo-stlying { text-align:center; padding:5px; }
    .card-bottom-area { padding-top:10px; font-weight:600; font-size:12px; }
    .card-bottom-area a { text-decoration:none; }
    i#star_icon.fa-lg { font-size:1.6em; }
    span#js-star-count { font-weight:600; }
    .board-link { text-decoration:none; font-weight:600; }
    .profile-link { text-decoration:none; }
    .post-info { font-size:11px; }
</style>
<div class="card card-styling mt-4" style="border:0;">
  <div class="card-body card-body-styling">

    <div class="star-partition">
      <a href="{% url 'like' subject.slug %}"
         style="text-decoration:none;"
         title="{{ subject.points.count }} points"
         id="js-star-subject">

         {% if subject in user.liked_subjects.all %}
           <i class="fa fa-star fa-lg" aria-hidden="true" id="star_icon"></i>
         {% else %}
           <i class="fa fa-star-o fa-lg" aria-hidden="true" id="star_icon"></i>
         {% endif %}
         <br>

         <span id="js-star-count">{{ subject.points.count }}</span>
      </a>
    </div>

    <div class="body-partition">
      <p class="post-info text-muted">
        <a href="{{ subject.board.get_absolute_url }}"
           title="visit board"
           class="board-link">b/{{ subject.board.slug }}</a> &bull;
        Posted by
        <a href="{% url 'user_profile' subject.author.username %}"
           title="view profile"
           class="profile-link">{{ subject.author.profile.screen_name }}</a>
        <span title="{{ subject.created|date:"D d M Y" }} | {{ subject.created|time:"H:i:s" }}">
           {{ subject.created|naturaltime }}
        </span>
      </p>
      <h5><a href="{{ subject.get_absolute_url }}" class="card-link">{{ subject.title|emoticons }}</a></h5>
      <p>{{ subject.body|urlize }}</p>

      {% if subject.photo %}
      <div class="card-photo-stlying">
        <img src="{{ subject.photo.url }}" width="80%">
      </div>
      {% endif %}

      <div class="card-bottom-area text-muted">
        <a href="{{ subject.get_absolute_url }}"
           title="{{ subject.comments.count }} comments">
           <i class="fa fa-comment fa-md" aria-hidden="true"></i> {{ subject.comments.count }} Comments
        </a> &bull;
        <a href="#" class="share_link" data-clipboard-text="{{ request.get_host }}{{ subject.get_absolute_url }}">
           <i class="fa fa-share fa-md" aria-hidden="true"></i> Share
        </a>
        <div style="float:right;">
          {% ifequal subject.author request.user %}
            <a href="{% url 'edit_subject' subject.slug %}"
               title="edit subject">
               <i class="fa fa-edit fa-lg"></i> Edit</a> &bull;
            <a href="{% url 'delete_subject' subject.slug %}"
               title="delete subject"
               id="delete_subject">
               <i class="fa fa-trash-o fa-lg"></i> Delete</a>
          {% else %}
            <a href="{% url 'report_subject' subject.slug %}"
               title="report this subject"
               id="report_link">
               <i class="fa fa-flag-o fa-lg"></i> Report</a>
          {% endifequal %}
        </div>
      </div>
    </div>
  </div>
</div>


<script type="text/javascript">
$(document).ready(function(){
  // Star or unstar a post
  $(document).on("click", "#js-star-subject", function () {
    {% if not request.user.is_authenticated %}
    window.location.href = "{% url 'login' %}";
    {% else %}
    var $star_count = $(this).find('#js-star-count');
    var $star_url = $(this).attr("href");
    var $star_icon = $(this).find('i.fa');
    $.ajax({
      url: $star_url,
      type: 'GET',
      success: function (data) {
        $star_count.text(data.total_points);

        if ($star_icon.hasClass('fa-star-o')) {
          $star_icon.removeClass('fa-star-o').addClass('fa-star');
        }
        else if ($star_icon.hasClass('fa-star')) {
          $star_icon.removeClass('fa-star').addClass('fa-star-o');
        } else {
          console.log('Unexpected error!');
        }
      }
    });
    {% endif %}
    return false;
  });

  // Show tooltip on click for 1 sec
  $('.share_link').on('click', function(e) {
    e.preventDefault();
    var elm = $(this);
    elm.tooltip({
      trigger: 'click',
      placement: 'bottom',
      title: 'Copied permalink!'
    });
    setTimeout(function(){
        elm.tooltip('hide');
    }, 1000);
  });

  // Report the subject
  $(document).on("click", "a#report_link",function () {
    {% if not request.user.is_authenticated %}
    window.location.href = "{% url 'login' %}";
    {% else %}
    var $report_url = $(this).attr("href");
    var $report_flag = $(this).find('i.fa');
    $.ajax({
      url: $report_url,
      type: 'GET',
      success: function (data) {
        if ($report_flag.hasClass('fa-flag-o')) {
          $report_flag.removeClass('fa-flag-o').addClass('fa-flag');
        }
        else {
          console.log('Unexpected error!');
        }
      }
    });
    {% endif %}
    return false;
  });

  // Delete the subject
  $("a#delete_subject").on("click", function () {
    {% if not request.user.is_authenticated %}
    window.location.href = "{% url 'login' %}";
    {% else %}
    var $element = $(this);
    var $delete_url = $(this).attr("href");
    var $delete_trash = $(this).find('i.fa');
    $.ajax({
      url: $delete_url,
      type: 'GET',
      success: function (data) {
        if ($delete_trash.hasClass('fa-trash-o')) {
          $delete_trash.removeClass('fa-trash-o').addClass('fa-trash');
          $('body').fadeOut("slow", "swing");
          window.location.replace('/');
        }
        else {
          console.log('Unexpected error!');
        }
      }
    });
    {% endif %}
    return false;
  });

  // Delete a comment
  $(document).on("click", "a#delete_comment",function () {
    {% if not request.user.is_authenticated %}
    window.location.href = "{% url 'login' %}";
    {% else %}
    var $element = $(this);
    var $delete_url = $(this).attr("href");
    var $delete_trash = $(this).find('i.fa');
    $.ajax({
      url: $delete_url,
      type: 'GET',
      success: function (data) {
        if ($delete_trash.hasClass('fa-trash-o')) {
          $delete_trash.removeClass('fa-trash-o').addClass('fa-trash');
          $element.closest("li.list-group-item").fadeOut();
        }
        else {
          console.log('Unexpected error!');
        }
      }
    });
    {% endif %}
    return false;
  });

  // Load new comments
  function load_new_comments() {
    var $last_comment_id = $("#comments_container li:last-child").attr('comment-id');
    $.ajax({
      url: '/load_new_comments/',
      data: {
        'subject':'{{subject.slug}}',
        'board':'{{board.slug}}',
        'last_comment_id': $last_comment_id,
      },
      cache: false,
      success: function (data) {
        $(comments_container).find("#no_comments").fadeOut(100);
        $(comments_container).append(data);
      },
      complete: function () {
        window.setTimeout(load_new_comments, 15000); // refresh after 15 seconds
      }
    });
  };
  load_new_comments();

  // Comment via ajax
  {% if request.user.is_authenticated %}
  $("#comment_form textarea").on("keydown", function (evt) {
    var keyCode = evt.which?evt.which:evt.keyCode;
    if (keyCode == 13) {
      var form = $("#comment_form");
      var comments_container = $("#comments_container");
      var input = $(this);
      $.ajax({
        data: $(form).serialize(),
        type: 'post',
        cache: false,
        beforeSend: function () {
          $(input).val("");
        },
        success: function (data) {
          $(comments_container).find("#no_comments").fadeOut();
          $(comments_container).append(data);
          $('html, body').stop().animate( {
            'scrollTop': input.offset().top-40
          }, 500, 'swing');
          input.focus();
        }
      });
      return false;
    }
  });
  {% else %}
  $("#comment_form textarea").on("focus", function() {
    $( this ).fadeOut( 500 );
    $("#comment_form").html('<div style="margin:10px;" id="login-first"><h6 class="text-center">Login required to comment this subject.</h6><a href="/login/" class="btn btn-block btn-primary"><b>Login</b></a></div>').fadeIn( 1000 );
    $('html, body').stop().animate( {
      'scrollTop': $("#login-first").offset().top-40
    }, 1000, 'swing');
  });
  {% endif %}

  // Reply to comment
  $(document).on("click", "#comments_container #reply_comment",function (e) {
    {% if not request.user.is_authenticated %}
    window.location.href = "{% url 'login' %}";
    {% else %}
    e.preventDefault();
    var $target = $(this).parent().find("a#commenter");
    var $target_id = $target.text();
    var $input_area = $("#comment_form textarea");
    $('html, body').stop().animate( {
      'scrollTop': $input_area.offset().top
    }, 500, 'swing');
    $input_area.focus();
    $input_area.val("u/"+$target_id+" :: ");
    {% endif %}
    return false;
  });

});
</script>

<script src="{% static 'js/clipboard.min.js' %}"></script>
<script type="text/javascript">
new ClipboardJS('.share_link');
</script>


<style>
#comments_container li a#commenter {
    border-radius: 100px;
    padding: 1px 10px;
    border: 1px solid #d6d6d6;
}
#comments_container li a#commenter:hover {
    border: 1px solid #3f51b5;
}
#comment_form #comment_text {
    background-color: #f8f9fa;
}
#comment_form #comment_text:focus {
    background-color: #fff;
}
</style>

{% if comments %}
<div class="card" style="margin:15px 0px;">
  <div class="card-header">
    Comments
  </div>
  <ul class="list-group list-group-flush" id="comments_container">
    {% for comment in comments %}
    <li class="list-group-item" comment-id="{{comment.id}}">
      <p>{{comment.body|emoticons}}
      <br><a href="{% url 'user_profile' comment.commenter.username %}" title="view profile" id="commenter" class="card-link">{{comment.commenter}}</a> &#8212;
      <span title="{{comment.created|date:"D d M Y"}} | {{comment.created|time:"H:i:s"}}">{{comment.created|naturaltime}}</span>

      {% ifequal user comment.commenter %}
      <a href="{% url 'delete_comment' comment.id %}" title="delete this comment" id="delete_comment"><i class="fa fa-trash-o"></i></a>
      {% else %}
      <a href="#" style="text-decoration:none;" title="reply to this comment" id="reply_comment"><i class="fa fa-reply"></i> Reply</a> &bull; <a href="{% url 'report_comment' comment.id %}" style="text-decoration:none;" title="report this comment" id="report_link"><i class="fa fa-flag-o"></i> Report</a>
      {% endifequal %}

    </p></li>
    {% endfor %}
  </ul>
</div>
{% else %}
<div class="card" style="margin:15px 0px;">
  <div class="card-header">
    Comments
  </div>
  <ul class="list-group list-group-flush" id="comments_container">
    <div style="padding:15px;" id="no_comments">
      <h6 class="text-center">No comments to display</h6>
    </div>
  </ul>
</div>
{% endif %}

<!-- Comment form -->
<p class="text-muted">
  {% if request.user.is_authenticated %}
  Comment as <a href="{% url 'user_profile' request.user.username %}"
                class="font-weight-bold">{{ request.user.profile.screen_name }}</a>
  {% else %}
  <a href="{% url 'login' %}"
     class="font-weight-bold">Login</a> to comment
  {% endif %}
</p>
<form role="form" method="post" onsubmit="return false" id="comment_form">
  {% csrf_token %}
  <textarea class="form-control" id="comment_text" rows="3" name="body" maxlength="2000" placeholder="Leave a comment"></textarea>
</form><br>

{% endblock %}

modele/templates/subjects/trending.html
{% extends "base.html" %}

{% block content %}

{% include "includes/page_heading.html" with text="Trending" %}
{% include "includes/partial_subject.html" with subjects=subjects %}

{% endblock content %}